### ISSUE TITLE
Lipika should permit schemes to disallow outputting some characters

### ISSUE THREAD

**Issue by deepestblue** [ratreya/lipika-engine#7] opened 2019-03-14 05:37 UTC
**Is your feature request related to a problem? Please describe.**
It looks like Lipika requires every scheme to support every possible character. I'd like for the `Ksharanam` scheme to not be able to input a standalone `VIRAMA` or a `NUKTA`, just as inputting a standalone `DEPENDENT UU` is meaningless. But removing such a mapping from the scheme results in an exception:

```
Application Specific Information:
Fatal error: 'try!' expression unexpectedly raised an error: LipikaEngine_OSX.EngineError.parseError("Cannot find mapping for [SIGN/VIRAMA]"): file /BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang_Fall2018/swiftlang_Fall2018-1000.11.42/src/swift/stdlib/public/core/ErrorType.swift, line 184
 
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libswiftCore.dylib            	0x0000000103dcf2c0 specialized _assertionFailure(_:_:file:line:flags:) + 144
1   libswiftCore.dylib            	0x0000000103e317a3 swift_unexpectedError + 307
2   com.daivajnanam.inputmethod.LipikaIME	0x00000001038afd24 LipikaController.refreshLiterators() + 4324
3   com.daivajnanam.inputmethod.LipikaIME	0x00000001038b9557 specialized LipikaController.init(server:delegate:client:) + 663
4   com.daivajnanam.inputmethod.LipikaIME	0x00000001038b1adf @objc LipikaController.init(server:delegate:client:) + 159
```

**Describe the solution you'd like**
I'd like for this constraint to not exist. When `lipika-engine` encounters a keystroke that does not have a mapped character in the current scheme, it could simply output the keystrokes.

**Comment by ratreya** [comment] 2019-09-09 03:01
With dependent vowels the problem is automatically solved by the fact that the same mappings when entered standalone output non-dependent vowels. But with Virama and Nukta, what should the expected behavior be? I can think of two options:

1. we can eat the input and not output anything which does not seem desirable
1. we could output the input keystroke without modification which may cause user confusion

Both options seem unintuitive to me and if I didn't know better would probably assume the IME is broken. The current philosophy is to try and output the closest sane mapping.

**Comment by ratreya** [comment] 2019-09-21 03:02
Also considered the fact that fonts don't prohibit you from rendering invalid glyphs, I am closing this as #wontfix. Let me know if you feel strongly about this.

**Closed by ratreya** 2019-09-21 03:02 UTC
